### ISSUE TITLE
Written against modified data_utils.py?

### ISSUE THREAD

**Issue by benjamincburns** [Marsan-Ma/tf_chatbot_seq2seq_antilm#1]
It appears that in `train.py` you are referencing items from `data_utils` which do not exist.

For instance, in the included `data_utils.py` there is no `prepare_dialog_data`, or `read_data`.  There is a `read_data` in the `translate.py` but it accepts no `reversed` kwarg.

I searched past revisions of the tensorflow/tensorflow repo, as well as tensorflow/models, and found no such code.

Could you please update the included `ref/data_utils.py` to include these modifications?

**Comment by Marsan-Ma** [comment]
Sorry for late response, it's in lib/data_util.py.
I guess you just missed it and have found the answer by yourself.
So I will close the issue.
