### ISSUE TITLE
Training Data Question

### ISSUE THREAD

**Issue by tnedev** [Marsan-Ma/tf_chatbot_seq2seq_antilm#10]
Why is each line in all the .txt files doubled?
Also, in this repository's training data I see lines which are repeated four-five rows?
I see the training data is mixed in between few languages. Does this work well so the bot understands multiple languages?

**Comment by Marsan-Ma** [comment]
All the corpus is in question-answer pairs, where odd lines are questions, even lines are corresponding answers.

The small corpus I leave in work directory as an example is lyric, and lyrics sometimes got repeated lines, so if the line repeated twice in original lyric, you will see 4 repeated lines.

I've added another corpus with the pre-trained model, you could see the new `go_example` script.

And yes, the seq2seq model is language-independent, since words after tokenize are all the same --- they are just tokens. So theoretically you could train multiple languages or even emoji in the same model.

**Comment by tnedev** [comment]
OK, 

But here is a small fraction of the OpenSubtittles corpus. 
You could see that each line is doubled and I was wondering why?

> i' m happy here .
> i' m happy here .
> i remember when mary and i planted these vines .
> i remember when mary and i planted these vines .
> you know , this will all pass .
> you know , this will all pass .
> why ?
> why ?
> are you leaving me ?
> are you leaving me ?
> we have to move on .
> we have to move on .
> you' ve grown old .
> you' ve grown old .
> you' ve done well .
> you' ve done well .
> we' ve both done well .
> we' ve both done well .
> get inside .
> get inside .
> get inside , fast !
> get inside , fast !
> jerusalem is on fire !
> jerusalem is on fire !
> it' s burning !
> it' s burning !
> the romans are killing everyone .
> the romans are killing everyone .
> move out of the way .
> move out of the way .
> we were sent here .
> we were sent here .
> god told us you would show yourself to us .
> god told us you would show yourself to us .
> he said you were dying .
> he said you were dying .
> peter ? ls that you ?
> peter ? ls that you ?
> i can' t tell .
> i can' t tell .
> what happened to you ?
> what happened to you ?
> i got old .
> i got old .
> you got old .
> you got old .
> this one i know .
> this one i know .
> no matter how old you get , i know you , nathaniel .
> no matter how old you get , i know you , nathaniel .
> you were the best shepherd because you had no sheep .
> you were the best shepherd because you had no sheep .
> rabbi .
> rabbi .
> i missed you .
> i missed you .
> and you ?
> and you ?
> they cut you .
> they cut you .
> your face .
> your face .
> who are you ?
> who are you ?
> john .
> john .
> the romans tortured me , cut my face .
> the romans tortured me , cut my face .
> i tried to tell them all about you .
> i tried to tell them all about you .
> then i saw jerusalem burn .
> then i saw jerusalem burn .
> i even saw the ark of the covenant stolen from the temple .
> i even saw the ark of the covenant stolen from the temple .
> they destroyed the temple , just like you said .
> they destroyed the temple , just like you said .
> the ark ?
> the ark ?
> there' s someone else outside .
> there' s someone else outside .
> be careful .
> be careful .
> he' s still angry .
> he' s still angry .
> judas .
> judas .
> judas , come in .
> judas , come in .
> didn' t you hear me ?
> didn' t you hear me ?
> i missed you so much .
> i missed you so much .
> he hears you .
> he hears you .
> he just won' t say anything .
> he just won' t say anything .
> he' s been fighting in jerusalem .
> he' s been fighting in jerusalem .
> look at his hands .
> look at his hands .
> there' s still blood on them .
> there' s still blood on them .
> judas , the master is speaking to you .
> judas , the master is speaking to you .
> answer him .
> answer him .
> traitor !
> traitor !
> your place was on the cross .
> your place was on the cross .
> that' s where god put you .
> that' s where god put you .
> when death got too close , you got scared and you ran away ... ... and you hid yourself in the life of some man .
> when death got too close , you got scared and you ran away ... ... and you hid yourself in the life of some man .
> we did what we were supposed to do !
> we did what we were supposed to do !
> you didn' t !
> you didn' t !

**Comment by loveJasmine** [comment]
I am also confused
