### ISSUE TITLE
./go_example output

### ISSUE THREAD

**Issue by tnedev** [Marsan-Ma/tf_chatbot_seq2seq_antilm#11]
Hi, 

So I've run the ./go_example but the output seems gibberish. 
Is this because the pretrained model is not trained enough or something else?

 [screen](http://imgur.com/a/xoFh2)

**Comment by tnedev** [comment]
After I played around a bit it seem this is because of the lack of good training and the model seems to converge on a few answers.

**Comment by Marsan-Ma** [comment]
Yeah, I also found this example model output suck.

You could try to enable the beam search and anti-LM by un-comment them in go_example, it will help a little. 

But obviously I set the dictionary size too small for this demo model, I'll train another one and upload it later.

**Comment by tnedev** [comment]
Sounds good. Will experiment again next weekend. 
I will also extract Bulgarian corpus and add it to your corpus repo. 

Thanks.

**Comment by Marsan-Ma** [comment]
I've updated the demo model, you may preview my chat log here:
https://github.com/Marsan-Ma/tf_chatbot_seq2seq_antilm/blob/master/example_chat.md

It's much better now after enlarging the dictionary size 50k => 100k.
