### ISSUE TITLE
go_example details

### ISSUE THREAD

**Issue by nabihach** [Marsan-Ma/tf_chatbot_seq2seq_antilm#13]
Can you please mention the parameters you used to train the go_example pre-trained model? E.g. number of layers, embedding size, hidden layer size, number of training iterations, perplexity achieved, and maximum output length?

**Comment by Marsan-Ma** [comment]
The default values are in lib/config.py, 
despite the --vocab_size 100000 --size 128 
as you could find in `go_example`.
