### ISSUE TITLE
Can you please elaborate more on the beam search . 

### ISSUE THREAD

**Issue by shamanez** [Marsan-Ma/tf_chatbot_seq2seq_antilm#27]
I was reading a lot about mean search . I have these questions on that . Let's say I select beam size of 3. So at every output time step  at the decoder we select top 3 words starting from first time step. 

**If I have 20 time steps I have to calculate 3^20 combinations . So I think it is not the way.** 

Can you please explain me how to drop unnecessary beams in the beam graph and get the desired combinations ?

**Comment by SaeedNajafi** [comment]
No it is not 3^20. Before going to the time step 3, you have 3 * 3 possible combinations from first and second time steps. Now before moving to the next time step, you select top 3 out of these 9 possible combinations.

**Comment by shamanez** [comment]
@SaeedNajafi  So at each time step we take the maximum number of combinations which have the highest probability and move further . Perfect !
