### ISSUE TITLE
Error in seq2seq.py

### ISSUE THREAD

**Issue by ManniSingh** [Marsan-Ma/tf_chatbot_seq2seq_antilm#3]
tf_chatbot_seq2seq_antilm/lib/seq2seq.py", line 1119, in model_with_buckets
    with ops.name_scope(name, "model_with_buckets", all_inputs):
TypeError: name_scope() takes 1 positional argument but 3 were given

**Comment by Marsan-Ma** [comment]
your tensorflow is dated, just upgrade it will solve this!

name_scope did only take 1 argument long time ago.
