### ISSUE TITLE
[Question] Where does rto (maybe rho) come from?

### ISSUE THREAD

**Issue by j-min** [Marsan-Ma/tf_chatbot_seq2seq_antilm#4]
Thank you for sharing your chatbot implementation!

Could you please explain how you implemented line below?
https://github.com/Marsan-Ma/tf_chatbot_seq2seq_antilm/blob/master/lib/seq2seq_model.py#L328

```
rto = (max(ep_step_loss) - min(ep_step_loss)) / (max(ep_rewards) - min(ep_rewards))
```
I've read your references such as https://arxiv.org/pdf/1606.01541v4.pdf.
and it seems like this comes from eq. (7) at page 5 of the paper.
```
∇J(θ) = ∇ log pRL(ˆa|[pi, qi])[m(ˆa, [pi, qi]) − b]` (7)
```
But I still cannot clearly understand what baseline & advantage function you used.

Thanks in advance :)

**Comment by Marsan-Ma** [comment]
No, I didn't follow this formula here. I just using a simpler one to try.
Feel free to modify the reinforcement learning cost function to your will, 
and if you got some good result, please share with us, thank you!!
