### ISSUE TITLE
Is this model giving proper output?

### ISSUE THREAD

**Issue by ajaymaity** [Marsan-Ma/tf_chatbot_seq2seq_antilm#7]
I am a newbie in Sequence to Sequence modelling. I trained this model (LSTM) and tried using the chat mode (when the perplexity was around 90) using the same keywords mentioned in the README doc.

**> tell me what you know about trump**
[{'eos': False, 'dec_inp': '_GO stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub poltergeist poltergeist', 'prob_ts': 1.6026612497510256e-62, 'prob': 1.6026612497510256e-62, 'prob_t': 0}, {'eos': False, 'dec_inp': '_GO stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub poltergeist', 'prob_ts': 1.6006921205145013e-62, 'prob': 1.6006921205145013e-62, 'prob_t': 0}, {'eos': False, 'dec_inp': '_GO stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub poltergeist poltergeist poltergeist', 'prob_ts': 1.59890017044286e-62, 'prob': 1.59890017044286e-62, 'prob_t': 0}, {'eos': False, 'dec_inp': '_GO stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub poltergeist 63rd', 'prob_ts': 1.5971538582203765e-62, 'prob': 1.5971538582203765e-62, 'prob_t': 0}, {'eos': False, 'dec_inp': '_GO stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub poltergeist stubhub poltergeist', 'prob_ts': 1.5969319874907339e-62, 'prob': 1.5969319874907339e-62, 'prob_t': 0}, {'eos': False, 'dec_inp': '_GO stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub poltergeist stubhub', 'prob_ts': 1.5962211039147383e-62, 'prob': 1.5962211039147383e-62, 'prob_t': 0}, {'eos': False, 'dec_inp': '_GO stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub 63rd', 'prob_ts': 1.5951962573956278e-62, 'prob': 1.5951962573956278e-62, 'prob_t': 0}, {'eos': False, 'dec_inp': '_GO stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub', 'prob_ts': 1.5942631107621106e-62, 'prob': 1.5942631107621106e-62, 'prob_t': 0}, {'eos': False, 'dec_inp': '_GO stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub 63rd poltergeist', 'prob_ts': 1.5937910490557992e-62, 'prob': 1.5937910490557992e-62, 'prob_t': 0}, {'eos': False, 'dec_inp': '_GO stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub stubhub poltergeist poltergeist 63rd', 'prob_ts': 1.5933914365934598e-62, 'prob': 1.5933914365934598e-62, 'prob_t': 0}]

^^ This is what I am getting. Is this a normal behaviour? Or am I doing something wrong? Is this the expected behavior with perplexity around 90? Should I wait till the perplexity reaches 50 or something?

Anybody who tried this model, please share your outputs, if possible.
Help much appreciated.
Thanks in advance.

**Comment by Marsan-Ma** [comment]
It depends on what you define "proper".
According to a friend in Google brain team, you need a lot of post-processing to get the result in the paper published by brain team. The seq2seq model is promising but not good enough for now.

But perplexity 90 is definitely too high, it should be much lower. 
Your output seems weird, maybe there's some issue in your training corpus?

**Comment by joa23** [comment]
See @ajaymaity  comments at https://github.com/Marsan-Ma/tf_chatbot_seq2seq_antilm/issues/6
I trained my model to perplexity 25 and still have the same issue.

**Comment by ddvladimir** [comment]
Try replacing  
**if ckpt and gfile.Exists(ckpt.model_checkpoint_path):**
with
  **if ckpt and gfile.Exists(ckpt.model_checkpoint_path+'.index'):**
in **seq2seq_model_utils.py**
It looks like in some tensorflow versions gfile.Exists expects old format of the checkpoints (ex: model.ckpt-20000), but tensorflow already stores them in the new format with .index, .meta and .data-xxxx-of-xxxx extension. 
It is causing this check  not see saved checkpoint, so it creates a new one instead
@ajaymaity @joa23

**Comment by Marsan-Ma** [comment]
Can't tell what happened in your case, which corpus are you using?
Try checking your **working_dir/data/chat.in** and **working_dir/data/vocab\*.in**, see if the content of this files make sense. If not, your corpus might not being parsed correctly.

By the way, whatever parameter you use in main.py by training, remember to add exactly the same while testing, since the saved model (tensorflow checkpoint) has no idea about these. (and actually they sometimes could be different while you know what you are doing.)

**Comment by Marsan-Ma** [comment]
Close this issue since no further activity.
By the way, I've just updated the code to latest tensorflow (v1.0.0), with a pre-trained model and a simple demo script `go_example`. I believe this will help you figure out the usage problem.
