### ISSUE TITLE
tensorflow 1.0 support

### ISSUE THREAD

**Issue by draugaslt** [Marsan-Ma/tf_chatbot_seq2seq_antilm#9]
What about tensorflow 1.0 support?

**Comment by draugaslt** [comment]
WARNING:tensorflow:From /home/tensorflow-chat-antilm/lib/seq2seq_model.py:195 in __init__.: all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.

and so on..

**Comment by Marsan-Ma** [comment]
As you wish, now it (only) support tensorflow-v1.0.0, please see the update note in README.md.
